### ISSUE TITLE
About: Warning: Failed prop type:

### ISSUE THREAD

**Issue by mozgbrasil** [front10/landing-page-create-react-app#2]
Hello good afternoon

About: Warning: Failed prop type: The prop `features[0].id` is marked as required in `Features`, but its value is `undefined`.

Can you help me please

I'm trying to integrate the landing page from the following repository example into my project

https://github.com/front10/landing-page-create-react-app

But see the error as images

![captura de tela de 2018-10-19 23-41-57](https://user-images.githubusercontent.com/17202780/47250592-3805f780-d3fa-11e8-9f3b-546d88d1f6ef.png)

**Comment by darielnoel** [comment]
Hi @mozgbrasil, thanks for letting us know. The Warning is because in the version 1.3.0 of the library we added this required validation for the **feature.id** field. We have made a fix already in the [**1.3.1**version](https://github.com/front10/landing-page-book/blob/dev/changelog.md#131-2018-10-20). Apologies for the inconvenience. Have a nice weekend ;)

**Comment by mozgbrasil** [comment]
Hello good Morning

Thanks, my friend, see no error

![captura de tela de 2018-10-22 10-14-51](https://user-images.githubusercontent.com/17202780/47294448-7a3e5d00-d5e3-11e8-9cf1-6882e16a2666.png)
